[theme]

primaryColor             = "#7D9D9C"
backgroundColor          = "#F0EBE3"
secondaryBackgroundColor = "#E4DCCF"
textColor                = "#576F72"
font                     = "sans serif"


# DEFINITIONS

# primaryColor:             Accent color for interactive elements.
# backgroundColor:          Background color for main content area.
# secondaryBackgroundColor: Background color for the sidebar and most interactive widgets.
# textColor:                Color used for almost all text.
# font:                     Font family for all text in the app, except code blocks.